### ISSUE TITLE
support .well-known/oidc-configuration

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti-browzer-runtime#162]
some IdP's (i'm looking at you Keycloak) use a url for authentication that seems to be nonstandard "/auth" vs "/authentication". Keycloak does however provide a .well-knonw/oidc-configuration endpoint, which shows you where the jwks endpoint is, where the auth endpoint is etc.

Enable browzer runtime to find/read/use a well-known/oidc-configuration endpoint

**Comment by Russell-Allen** [comment]
For reference, that well known configuration document is defined in the OIDC Discovery spec here:  https://openid.net/specs/openid-connect-discovery-1_0.html

**Comment by rentallect** [comment]
Now available in `0.51.0`
