### ISSUE TITLE
Position BrowZer icon relative to lower right corner, not absolutely

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti-browzer-runtime#308]
right now if you move the browZer icon somewhere, then make the window BIGGER, the viewport of the windows is still acceptable to the absolute position of the icon which is unexpected. I expected if i put the icon in the lower right and then make the window bigger, it'd be in the lower right corner still.  Same if i positioned it in the lower left corner and made the window taller.

![browzer-icon-loc](https://github.com/openziti/ziti-browzer-runtime/assets/46322585/0ec3042f-56e2-432d-83eb-cd5157b1e9a0)

**Comment by rentallect** [comment]
fixed in `0.61.3`
